addons:
  postgresql: "9.6"
language: rust
rust:
  - nightly
cache: cargo
before_script:
  - psql -c 'create database whosin_test;' -U postgres
script:
  - cargo test
  - cargo build
branches:
  only:
    - master
